parameters:
    nixilla.api.data_collector.class: Nixilla\Api\LoggerBundle\DataCollector\ApiDataCollector
    nixilla.api.logger.class: Nixilla\Api\LoggerBundle\Logger\ApiLogger


services:

    nixilla.api.data_collector:
        class: "%nixilla.api.data_collector.class%"
        arguments: [ "@nixilla.api.logger" ]
        tags:
            - { name: "data_collector", template: "@NixillaApiLogger/DataCollector/api", id: "api" }

    nixilla.api.logger:
        class: "%nixilla.api.logger.class%"
        arguments: [ "@logger", "%kernel.debug%" ]

    nixilla.curl_format.twig_extension:
        class: Nixilla\Api\LoggerBundle\Twig\CurlFormatter
        public: true
        tags:
            - { name: twig.extension }